version: "3.7"
services:
  dev:
    image: microservice:dev
    container_name: dev
    ports:
      - ${DEV_PORT}:5001
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      - PORT=${DEV_PORT}
      - ENV=development
  prod:
    image: microservice:prod
    container_name: prod
    ports:
      - ${PROD_PORT}:5002
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      - PORT=${PROD_PORT}
      - ENV=production
  release:
    image: microservice:release
    container_name: release
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment: 
      - PORT=5000
      - ENV=release   
    networks: 
      - release

networks: 
  release:
    driver: bridge